### ISSUE TITLE
Remove publishConfig from package.json

### ISSUE THREAD

**Issue by sashokbg** [apideck-libraries/better-ajv-errors#21]
Hello,

Unfortunately due to a limitation in npm, the "publishConfig" key cannot be overridden when using "npm publish".
This makes the package unusable in internal private repositories.

Is it possible to remove the following from the package.json ?

```
  "publishConfig": {
    "registry": "https://registry.npmjs.org",
    "access": "public"
  },
```

**Comment by elsmr** [comment]
Fixed in [v0.3.6](https://github.com/apideck-libraries/better-ajv-errors/releases/tag/v0.3.6) :smile:
