### ISSUE TITLE
Guidance re: combining schemas?

### ISSUE THREAD

**Issue by dmitrc** [apideck-libraries/better-ajv-errors#26]
Is there any way to use [combined schemas](https://ajv.js.org/guide/combining-schemas.html#combining-schemas-with-ref) with this library?
At the moment it seems like this library only accepts a single schema object (rather than **array** as base Ajv does).

If validation fails on any of the properties referenced in _another file_, you will get an exception like this:
```
error - TypeError: Cannot read properties of undefined (reading 'properties')
    at ...\node_modules\@apideck\better-ajv-errors\dist\better-ajv-errors.cjs.development.js:142:45
    at Array.map (<anonymous>)
    at betterAjvErrors (...\node_modules\@apideck\better-ajv-errors\dist\better-ajv-errors.cjs.development.js:120:24)
```
```
var _safeJsonPointer = safeJsonPointer({
            object: schema,
            pnter: suggestionPointer,
            fallback: {
              properties: {}
            }
          }),
              properties = _safeJsonPointer.properties;
                                 ^-- [!] undefined
```

**Comment by jonaslagoni** [comment]
Since I cant see your code, I guess the setup you have is slightly incorrect according to AJV, this test pass:

```ts
const validateCombined = ajv.addSchema(combinedSchema).compile(schema);
validateCombined(data);
const betterErrors = betterAjvErrors({ data, schema, errors: validateCombined.errors });
```

Feel free to re-open if anything comes up :v:

**Comment by jonaslagoni** [comment]
Added it as a test here; https://github.com/apideck-libraries/better-ajv-errors/pull/29
